import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/utils/Navbar";
import Footer from "./components/utils/Footer";
import Providers from "./components/Providers";


export const metadata: Metadata = {
  title: "NOORIX_LEARNING",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      > 
        <Providers>
          <Navbar/>
            <div className="min-h-screen py-18 bg-slate-50">
              { children}
            </div>
           <Footer />
        </Providers>
      </body>
    </html>
  );
}
